<?php

namespace App\Http\Controllers\Admin;

use A17\Twill\Http\Controllers\Admin\ModuleController;
use App\Models\Order;
use App\Models\OrderProducts;
use Illuminate\Http\Request;


class OrderController extends ModuleController
{
    protected $moduleName = 'orders';

    protected $titleColumnKey = 'name';

    protected $indexOptions = [
//        'permalink' => false,
        'skipCreateModal' => true,
        'editInModal' => false,
        'create' => true,
    ];
    protected $previewView = 'orders/preview';

    protected $indexColumns = [
        'name' => [ // field column
            'title' => 'Name',
            'field' => 'name',
        ],
        'shipping_address' => [ // field column
            'title' => 'Cím',
            'field' => 'shipping_address',
        ],
        'phone' => [ // field column
            'title' => 'Telefonszám',
            'field' => 'phone',
        ],
        'order_number' => [ // field column
            'title' => 'Order number',
            'field' => 'order_number',
        ],
    ];

    public function edit($id, $submoduleId = null)
    {
        $order = Order::query()->with([
            'user','products','products.options','products.products'])->findOrFail($id);

        return view('admin.orders/preview',compact('order'));
//        return parent::edit($id, $submoduleId); // TODO: Change the autogenerated stub
    }

    public function editing($id, $submoduleId = null)
    {
        return parent::edit($id, $submoduleId); // TODO: Change the autogenerated stub
    }

    public function report(Request $request)
    {
        $orders = null;
        $date = null;

        if ($request->has('date')) {
            $date = $request->date;
            $orders = OrderProducts::query()
                ->with('products','options','products.options')
                ->where('menu_date',$date)
                ->get()
                ->sortBy('products.title',SORT_REGULAR,false);
        }

        return view('admin/orders/report',compact('orders','date'));
    }
}
