<?php

namespace App\Repositories;

use A17\Twill\Repositories\Behaviors\HandleRevisions;
use A17\Twill\Repositories\ModuleRepository;
use App\Models\Day;
use Carbon\Carbon;

class DayRepository extends ModuleRepository
{
    use HandleRevisions;

    public function __construct(Day $model)
    {
        $this->model = $model;
    }

    public function afterSave($object, $fields)
    {
        $this->updateBrowser($object,$fields,'products');

        parent::afterSave($object, $fields); // TODO: Change the autogenerated stub
    }


    public function getFormFields($object) {

        // don't forget to call the parent getFormFields function
        $fields = parent::getFormFields($object);

        $fields['browsers']['products'] = $this->getFormFieldsForBrowser($object, 'products');
        $fields['date'] = Carbon::now()->format('Y-m-d');

        // return fields
        return $fields;
    }
}
