<?php

namespace App\Repositories;


use A17\Twill\Repositories\ModuleRepository;
use App\Models\Option;

class OptionRepository extends ModuleRepository
{


    public function __construct(Option $model)
    {
        $this->model = $model;
    }

    public function afterSave($object, $fields)
    {
        // Set net price
        if (intval($object->getAttribute('gross_price')) !== 0) {
            $object->net_price = $object->gross_price / (($object->tax + 100) / 100);
            $object->save();
        }

        parent::afterSave($object, $fields); // TODO: Change the autogenerated stub
    }
}
