<?php

namespace App\Repositories;

use A17\Twill\Repositories\Behaviors\HandleSlugs;
use A17\Twill\Repositories\Behaviors\HandleMedias;
use A17\Twill\Repositories\Behaviors\HandleRevisions;
use A17\Twill\Repositories\ModuleRepository;
use App\Models\Product;

class ProductRepository extends ModuleRepository
{
    use HandleSlugs, HandleMedias, HandleRevisions;

    public function __construct(Product $model)
    {
        $this->model = $model;
    }

    public function afterSave($object, $fields)
    {
        $this->updateBrowser($object,$fields,'options');

        // Set net price
        if (intval($object->getAttribute('gross_price')) !== 0) {
            $object->net_price = $object->gross_price / (($object->tax + 100) / 100);
            $object->save();
        }

        parent::afterSave($object, $fields); // TODO: Change the autogenerated stub
    }

    public function getFormFields($object) {
        // don't forget to call the parent getFormFields function
        $fields = parent::getFormFields($object);

        // get fields for a browser
        $fields['browsers']['options'] = $this->getFormFieldsForBrowser($object, 'options');

        // return fields
        return $fields;
    }
}
